---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-java-app
  labels:
    app: sample-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-java-app      
  template:
    metadata:
      labels:
        app: sample-java-app
    spec:
      containers:
      - name: sample-java-app
        image: unicredit/sample-java-app:latest
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: sample-java-app
spec:
  selector:
    app: sample-java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
